component: api
tier: backend
parent: backend
environment: test

name: mtaf-influx-db
image: influxdb
imageTag: latest
imagePullPolicy: Always
containerPort: 8086
replicas: 1

configname: mtaf-influx-db-test-configmap

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

# ✅ Environment variables passed into the container
env:
  - name: DOCKER_INFLUXDB_INIT_MODE
    value: "setup"
  - name: DOCKER_INFLUXDB_INIT_USERNAME
    value: "rajesh23427"
  - name: DOCKER_INFLUXDB_INIT_PASSWORD
    value: "Automation@1234"
  - name: DOCKER_INFLUXDB_INIT_ORG
    value: "mtaf"
  - name: DOCKER_INFLUXDB_INIT_BUCKET
    value: "jmeter-results"

data: {}

# ✅ Ingress Configuration (choose host or path or both)
ingress:
  enabled: true
  className: nginx

  # --- Host-based routing ---
  hosts:
    - host: influx.test.app.yokai.com   # change to your domain
      paths:
        - path: /
          pathType: Prefix
          service:
            name: mtaf-influx-db
            port: 8086

  # --- Path-based routing ---
  defaultPaths:
    - path: /influxdb
      pathType: Prefix
      service:
        name: mtaf-influx-db
        port: 8086
