name: mtaf-influx-db
tier: backend
parent: backend
component: api
image: influxdb
imageTag: latest
imagePullPolicy: Always
containerPort: 8086
configname: mtaf-influx-db-test-configmap
replicas: 1
environment: test
resources:
  requests:
    memory: "200Mi"
    cpu: "100m"
  limits:
    memory: "300Mi"
    cpu: "500m"

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: api.yokai.com
      paths:
        - path: /mtaf-influx-db-test
          service:
            name: backend-service
            port: 8086
#####################
data:
