name: mtaf-influx-db
tier: backend
parent: backend
component: api
image: influxdb
imageTag: latest
imagePullPolicy: Always
containerPort: 8086
configname: mtaf-influx-db-test-configmap
replicas: 1
environment: test
resources:
  requests:
    memory: "200Mi"
    cpu: "100m"
  limits:
    memory: "300Mi"
    cpu: "500m"

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: api.yokai.com
      paths:
        - path: /mtaf-influx-db-test
          service:
            name: backend-service
            port: 8086
#####################
env:
  - name: DOCKER_INFLUXDB_INIT_MODE
    value: setup
  - name: DOCKER_INFLUXDB_INIT_USERNAME
    value: rajesh23427
  - name: DOCKER_INFLUXDB_INIT_PASSWORD
    value: Automation@1234
  - name: DOCKER_INFLUXDB_INIT_ORG
    value: mtaf
  - name: DOCKER_INFLUXDB_INIT_BUCKET
    value: jmeter-results
data:
