{{- /*
  At least one quota must be configured.
*/}}
{{- if not .Values.quota }}
{{- fail ".Values.quota is not set" }}
{{- end -}}

{{- $releaseNamespace := .Release.Namespace }}
{{- $browserControl := false }}
{{- range $name, $quota := .Values.quota }}
{{- if eq $quota.namespace $releaseNamespace }}
{{- $browserControl = true }}
{{- end }}
{{- end }}
{{- if .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
rules:
- apiGroups:
  - moon.aerokube.com
  resources:
  - licenses
  - licenses/status
  verbs:
  - get
  - watch
  - list
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
{{- if $browserControl }}
  - pods/log
  - configmaps
{{- end }}
  verbs:
  - get
  - watch
  - list
  - update
  - patch
{{- if $browserControl }}
  - create
  - delete
{{- end }}
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - watch
  - list
  - update
  - patch
- apiGroups:
  - moon.aerokube.com
  resources:
  - quotas
  - configs
  - browsersets
  - devicesets
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - moon.aerokube.com
  resources:
  - configs
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
