{{- template "check.quota" . }}
{{- template "check.quota.namespaces" . }}

{{- $releaseName := .Release.Name }}
{{- $releaseNamespace := .Release.Namespace }}
{{- range $name, $quota := .Values.quota }}
{{- if ne $quota.namespace $releaseNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
  namespace: {{ $quota.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - configmaps
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
  namespace: {{ $quota.namespace }}
roleRef:
  kind: Role
  name: {{ $name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ $releaseName }}
  namespace: {{ $releaseNamespace }}
{{- end }}
{{- end }}

