---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.serviceAccountAnnotations }}
  annotations:
  {{- range $key, $value := .Values.serviceAccountAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
