{{- range $name, $quota := .Values.quota }}
  {{- if or (not $quota) (not $quota.namespace) }}
  {{- fail (printf "quota %s namespace is not set" $name) }}
  {{- end }}
{{- if $quota.serviceAccountName }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $quota.serviceAccountName }}
  namespace: {{ $quota.namespace }}
  {{- if $quota.serviceAccountAnnotations }}
  annotations:
  {{- range $key, $value := $quota.serviceAccountAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}