{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.component }}
    app.kubernetes.io/tier: {{ .Values.tier }}
    app.kubernetes.io/environment: {{ .Values.environment }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" | quote }}
  rules:
    # --- Host-based routing (appname.app.yokai.com) ---
    - host: {{ .Values.name }}.{{ .Values.ingress.baseDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name }}
                port:
                  number: {{ .Values.containerPort }}

    # --- Path-based routing (app.yokai.com/appname) ---
    - host: {{ .Values.ingress.baseDomain }}
      http:
        paths:
          - path: /{{ .Values.name }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name }}
                port:
                  number: {{ .Values.containerPort }}
{{- end }}
