apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ahq-test-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: default
  namespace: ahq-test