---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- if and .Values.moon.serviceaccount .Values.moon.serviceaccount.annotations }}
  annotations:
  {{- range $key, $value := .Values.moon.serviceaccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
