name: ahq-grid-server
tier: backend
parent: ahq-backend
component: api
image: aerokube/moon
imageTag: latest
imagePullPolicy: Always
containerPort: 4444
configname: ahq-grid-server-prod-configmap
replicas: 1
environment: prod
resources:
  requests:
    memory: "200Mi"
    cpu: "100m"
  limits:
    memory: "300Mi"
    cpu: "1000m"
#####################
data:
