{{- if and (eq .Values.moon.resourcequotacontrol false) (gt (int .Values.moon.sessionsLimit) 0) }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: max-moon-sessions
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    pods: "{{ add .Values.moon.sessionsLimit ( .Values.moon.replicas | default 2 ) }}"
{{- end }}
