---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - configmaps
  - secrets
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - get
  - watch
  - list
{{- if .Values.moon.resourcequotacontrol }}
  - create
  - update
  - patch
  - delete
{{- end }}
