---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: {{ .Release.Namespace }}
  labels:
stringData:
  s3.accessKey: "{{ if .Values.moon.config.s3 }}{{- if .Values.moon.config.s3.accessKey }}{{ .Values.moon.config.s3.accessKey }}{{ end }}{{ end }}"
  s3.secretKey: "{{ if .Values.moon.config.s3 }}{{- if .Values.moon.config.s3.secretKey }}{{ .Values.moon.config.s3.secretKey }}{{ end }}{{ end }}"
