---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-browsers
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    moon: browser
  clusterIP: None
  publishNotReadyAddresses: true
