apiVersion: batch/v1
kind: Job
metadata:
  name: ahq-grid-server-post-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: sleep
          image: alpine:latest
          command: ["sleep", "3"]
      restartPolicy: Never
  backoffLimit: 0
