apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/part-of: {{ .Values.parent }}
spec:
  selector:
    app: {{ .Values.name }}
    tier: {{ .Values.tier }}
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}