apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ahq-backend-test
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/yashrajgosavi/argo-cd-helm-charts
      revision: main
      directories:
      - path: release/charts/*
      - exclude: true      
        path: release/charts/addon-apps
  template:
    metadata:
      name: '{{path.basename}}-test'
    spec:
      project: ahq-test
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        helm:
          valueFiles:
            - values-test.yaml
        repoURL: https://github.com/yashrajgosavi/argo-cd-helm-charts
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: ahq-test