apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.name }}
  namespace: argocd
spec:
  project: {{ .Values.project }}
  source:
    helm:
      valueFiles: 
        - values-prod.yaml
    repoURL: {{ .Values.repoURL }}
    targetRevision: main
    path: release/charts/auth-services
  destination:
    server: {{ .Values.server }}
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  