apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configname }} 
  labels:
      app: {{ .Values.name }}
      tier: backend
      env: {{ .Values.environment }}
data:
{{ toYaml .Values.data | indent 2 }}