apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: {{ .Values.component }}
    app.kubernetes.io/part-of: {{ .Values.parent }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        tier: {{ .Values.tier }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        securityContext:
          privileged: {{ .Values.securityContext.privileged }}
          capabilities:
            add: {{ .Values.capabilities.add }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: JVM_OPTS
          value: "-Xmx128M"     
        envFrom:
          - configMapRef:
              name: {{ .Values.configname }}                        
        resources:
          {{ .Values.resources | toYaml | nindent 10 | trim }}     
        ports:
        - containerPort: {{ .Values.containerPort }}
        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          httpGet:
            scheme: HTTP
            path: /wd/hub
            port: {{ .Values.containerPort }}
        # livenessProbe: 
        #   httpGet: 
        #     path: /wd/hub
        #     port: {{ .Values.containerPort }}
