---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configs.moon.aerokube.com
spec:
  group: moon.aerokube.com
  names:
    kind: Config
    listKind: ConfigList
    plural: configs
    shortNames:
    - conf
    singular: config
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              additionalTrustedCAs:
                type: string
              containers:
                additionalProperties:
                  default: {}
                  properties:
                    repository:
                      type: string
                    resources:
                      default: {}
                      properties:
                        limits:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          default: {}
                          type: object
                        requests:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          default: {}
                          type: object
                      type: object
                    securityContext:
                      properties:
                        allowPrivilegeEscalation:
                          type: boolean
                        capabilities:
                          properties:
                            add:
                              items:
                                type: string
                              type: array
                            drop:
                              items:
                                type: string
                              type: array
                          type: object
                        privileged:
                          type: boolean
                        procMount:
                          type: string
                        readOnlyRootFilesystem:
                          type: boolean
                        runAsGroup:
                          format: int64
                          type: integer
                        runAsNonRoot:
                          type: boolean
                        runAsUser:
                          format: int64
                          type: integer
                        seLinuxOptions:
                          properties:
                            level:
                              type: string
                            role:
                              type: string
                            type:
                              type: string
                            user:
                              type: string
                          type: object
                        seccompProfile:
                          properties:
                            localhostProfile:
                              type: string
                            type:
                              type: string
                          required:
                          - type
                          type: object
                        windowsOptions:
                          properties:
                            gmsaCredentialSpec:
                              type: string
                            gmsaCredentialSpecName:
                              type: string
                            hostProcess:
                              type: boolean
                            runAsUserName:
                              type: string
                          type: object
                      type: object
                    version:
                      type: string
                  type: object
                type: object
              group:
                default: {}
                properties:
                  id:
                    default: 4096
                    format: int64
                    type: integer
                  name:
                    default: user
                    type: string
                    pattern: ^[a-z_][a-z0-9_-]{0,31}\${0,1}$
                type: object
              serviceAccountName:
                type: string
                pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                default: default
              sessionTimeout:
                type: string
                pattern: ^[0-9][0-9]*[smh]$
                default: 5m
              storage:
                default: {}
                properties:
                  accessKey:
                    type: string
                    default: ''
                  bucket:
                    type: string
                    default: ''
                  endpoint:
                    type: string
                    default: ''
                  filename:
                    type: string
                    default: ''
                  pattern:
                    type: string
                    default: ''
                  secretKey:
                    type: string
                    default: ''
                  secretRef:
                    type: object
                    properties:
                      name:
                        type: string
                        pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                      accessKey:
                        type: string
                      secretKey:
                        type: string
                    required:
                    - name
                  noProxy:
                    type: string
                    default: ''
                  httpProxy:
                    type: string
                    default: ''
                  httpsProxy:
                    type: string
                    default: ''
                  metadata:
                    type: boolean
                    default: true
                type: object
              user:
                default: {}
                properties:
                  id:
                    format: int64
                    type: integer
                    default: 4096
                  name:
                    type: string
                    pattern: ^[a-z_][a-z0-9_-]{0,31}\${0,1}$
                    default: user
                type: object
            type: object
        type: object
    served: true
    storage: true
