---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devicesets.moon.aerokube.com
spec:
  group: moon.aerokube.com
  names:
    kind: DeviceSet
    listKind: DeviceSetList
    plural: devicesets
    singular: deviceset
    shortNames:
    - devices
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              devices:
                additionalProperties:
                  properties:
                    height:
                      format: int32
                      type: integer
                    pixelRatio:
                      type: number
                    printVersion:
                      type: boolean
                      default: false
                    userAgent:
                      type: string
                    width:
                      format: int32
                      type: integer
                  required:
                  - height
                  - pixelRatio
                  - userAgent
                  - width
                  type: object
                type: object
            required:
            - devices
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
